# render.yaml

services:
  - name: zookeeper
    type: web
    env: docker
    plan: standard
    dockerfilePath: ./zookeeper/Dockerfile
    disk:
      name: zookeeper-data
      sizeGB: 10
    envVars:
      - key: ZOOKEEPER_CLIENT_PORT
        value: "2181"
      - key: ZOOKEEPER_TICK_TIME
        value: "2000"

  - name: kafka
    type: web
    env: docker
    plan: standard
    dockerfilePath: ./kafka/Dockerfile
    disk:
      name: kafka-data
      sizeGB: 20
    envVars:
      - key: KAFKA_ZOOKEEPER_CONNECT
        value: zookeeper:2181
      - key: KAFKA_ADVERTISED_LISTENERS
        value: PLAINTEXT://kafka:9092
      - key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        value: "1"
      - key: KAFKA_BROKER_ID
        value: "1"
